#  http://localhost:4444/ui#  -> UI Selenium HUB
#  http://localhost:7999/  -> noVnc UI for Chrome debugging (if it is activated -> it will work only for 1 node!)
# https://github.com/SeleniumHQ/docker-selenium/releases/tag/4.9.1-20230508 -> image for Chrome ver: 113.0.5672.63
version: "3"
services:
  selenium-hub:
    image: selenium/hub:4.9.1-20230508
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.9.1-20230508
    container_name: chrome-hub
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    ports:
      - "7999:7900"
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tests-container
    depends_on:
      chrome:
        condition: service_started
    volumes:
      - ./allure-results:/apps/qa/allure-results
      - ./logs:/apps/qa/logs
    environment:
      - BROWSER=CHROME_REMOTE